<a href="https://colab.research.google.com/github/Arindamthander/Robotron/blob/main/PRML_LAB_06.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Construct a random matrix $A_{5\times 11}$ of order $5\times 11$. Compute SVD decomposition of the matrix $A$ using Python code. Compare your result with the inbuilt function.

In [23]:
import numpy as np


rows = 5
col = 11
A = np.random.rand(rows,col, )

## by method
K = A.T @ A
eigenvalues, eigenvectors = np.linalg.eig(K)

order = np.argsort(eigenvalues)[::-1]
eigenvalues = eigenvalues[order]
eigenvectors = eigenvectors[:, order]

uniteig = eigenvectors / np.linalg.norm(eigenvectors, axis=0)

sigma_2 = np.sqrt(np.abs(eigenvalues))
sigma = np.diag(sigma_2)
trunc_sigma = sigma[:5,0:]
Vt = uniteig.T

K_2 = A @ A.T
eigenvalues_2, eigenvectors_2 = np.linalg.eig(K_2)
order = np.argsort(eigenvalues_2)[::-1]
eigenvalues_2 = eigenvalues_2[order]
eigenvectors_2 = eigenvectors_2[:, order]

U = eigenvectors_2

## Directly done
U_np, sigma_np, Vt_np = np.linalg.svd(A)

print("U")
print(U)
print("U_dir")
print(U_np)

print("Vt")
print(Vt)
print("V_dir")
print(Vt_np)

print("sigma")
print(sigma)
print("sigma_dir")
print(sigma_np)

U
[[ 0.43252236  0.69734541 -0.20006787  0.25876422  0.46866589]
 [ 0.44019363 -0.43597182  0.14996202  0.76198293 -0.11424339]
 [ 0.57091606 -0.34230961  0.32708675 -0.5280282   0.41361753]
 [ 0.41835544 -0.14809175 -0.78193596 -0.22850415 -0.37337589]
 [ 0.34378417  0.42957062  0.46805411 -0.14627086 -0.67587847]]
U_dir
[[-0.43252236  0.69734541  0.20006787 -0.25876422  0.46866589]
 [-0.44019363 -0.43597182 -0.14996202 -0.76198293 -0.11424339]
 [-0.57091606 -0.34230961 -0.32708675  0.5280282   0.41361753]
 [-0.41835544 -0.14809175  0.78193596  0.22850415 -0.37337589]
 [-0.34378417  0.42957062 -0.46805411  0.14627086 -0.67587847]]
Vt
[[-2.93846498e-01+0.j         -3.05025114e-01+0.j
  -2.81739402e-01+0.j         -2.16494982e-01+0.j
  -3.41019912e-01+0.j         -2.96936332e-01+0.j
  -3.37093667e-01+0.j         -4.40443713e-01+0.j
  -2.97399412e-01+0.j         -1.80602919e-01+0.j
  -2.47415341e-01+0.j        ]
 [-4.51762199e-01+0.j          1.62468966e-01+0.j
   8.91680138e-02+0.j     

In [35]:
import numpy as np

# Create a random matrix A of size 5x11
A = np.random.rand(5, 11)

# Compute SVD decomposition without using built-in function
def svd_custom(A):
    # Calculate covariance matrix
    covariance_matrix = A.T @ A

    # Eigenvalue decomposition of covariance matrix
    eigenvalues, eigenvectors = np.linalg.eigh(covariance_matrix)

    # Sort eigenvalues and eigenvectors in descending order
    order = np.argsort(eigenvalues)[::-1]
    eigenvalues = eigenvalues[order]
    eigenvectors = eigenvectors[:, order]

    # Construct Sigma matrix
    sigma = np.sqrt(np.abs(eigenvalues))

    # Construct U and V matrices

    Vt = eigenvectors.T
    U = npdot(np.dot(A,np.linalg.inverse(Vt)),np.linalg()

    return U, sigma, Vt

# Compute SVD using the custom function
U_custom, sigma_custom, Vt_custom = svd_custom(A)

# Compute SVD using the built-in function for comparison
U_np, sigma_np, Vt_np = np.linalg.svd(A, full_matrices=False)

# Compare the results
print("U (Custom vs NumPy):")
print(U_custom)
print(U_np)

print("\nSigma (Custom vs NumPy):")
print(sigma_custom)
print(sigma_np)

print("\nVt (Transpose) (Custom vs NumPy):")
print(Vt_custom)
print(Vt_np)


U (Custom vs NumPy):
[[-0.76812473 -0.1341119  -0.5112352  -0.50919603 -0.13366853 -1.18704925
  -0.23504024 -0.13900758 -0.83306245 -0.56955138 -0.7161618 ]
 [-0.73806308 -0.45985176 -0.52841455 -0.88444226 -0.09562288 -1.98553412
  -0.22956111 -0.18266762 -0.74783448 -0.3655304  -1.0379299 ]
 [-0.60124091 -0.37920281 -0.45726071 -0.522707   -0.52714168 -0.02793525
  -0.46546344 -0.4101766  -0.33284884 -0.33282666 -0.11326148]
 [-0.09013287 -0.57166981 -0.26060094 -0.4143059  -0.11505425 -2.32943581
  -0.24603572 -0.32074115 -0.50682051 -0.4830965  -1.26816328]
 [-0.41031165 -0.34749288 -0.04584723 -0.39870249 -0.45625156 -3.50788878
  -0.35898724 -0.17629689 -0.12022654 -0.56841282 -0.83852503]]
[[-0.41483374  0.17936854  0.51682743  0.33686219  0.64432381]
 [-0.49826608 -0.06063794  0.54548796 -0.18312276 -0.64572664]
 [-0.42264803  0.75879321 -0.40725417 -0.28224533 -0.00911714]
 [-0.43013904 -0.56561476 -0.2243802  -0.56421999  0.35548513]
 [-0.46475041 -0.26165392 -0.46811308  0.

2. Take a photo of your own of size  $>2 mb$. Use the SVD technique taught in class to compress the size of the original image to $60\%$. Display the compressed image. Also, keep increasing he compression size, and identify till what compression ratio that you can recognize yourself.

In [ ]:
import

3. Consider the [breast cancer dataset](https://archive.ics.uci.edu/dataset/17/breast+cancer+wisconsin+diagnostic). Write a python code to:

*   Use Principal Component Analysis (PCA) to reduce the 30 features in this dataset to lower dimension.
*   Then use the dimensionality reduced data to classify the tumor as malignant and benign.